T_max: 10
batch_size: 32
check_val_every_n_epoch: 1
competition_name: blood-vessel-segmentation
debug: true
decoder_channels:
- 512
- 256
- 128
- 64
- 64
dropout: 0.2
encoder_channels:
- 64
- 128
- 256
- 512
- 512
encoder_name: seresnext50_32x4d
epochs: 2
eta_min: 1.0e-06
exp_category: baseline
exp_name: exp011_hydra
img_height: 512
img_width: 512
in_channels: 1
input_data_dir: /kaggle/input/blood-vessel-segmentation
input_dir: /kaggle/input
label_df: /kaggle/working/label_512_512.csv
loss_type: dice
lr: 0.0001
minmax_df_path: None
model_name: SegModel
monitor: val_loss
monitor_mode: min
num_workers: 2
out_channels: 1
output_dir: /kaggle/working
overlap_rate: 0.2
object_min_size: 0
patch_height: 768
patch_width: 768
phase: train
pretrained: true
processed_data_dir: /kaggle/working/_processed
save_dir: /kaggle/working/exp011_hydra
save_weight_dir: /kaggle/working/exp011_hydra/weights
seed: 42
slice_num: 1
stride_height: 512
stride_width: 512
threshold: 0.5
train_data_name:
- kidney_1_dense
train_df: /kaggle/working/train_512_512.csv
use_batchnorm: true
valid_data_name:
- kidney_2
valid_df: /kaggle/working/valid_512_512.csv
